"""Automated validation script to verify cross-row theory/lab clash detection."""
import sys
import os

# Ensure the app directories are visible to python
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from utils.slots import intervals_of_slot, any_overlap
from utils.clash import combo_clash


def test_wednesday_afternoon_clash():
    print("Executing Validation Test Suite...")
    print("-" * 50)

    # 1. Fetch the exact intervals generated by your updated slots.py matrix
    tcc2_intervals = intervals_of_slot("TCC2")
    l40_intervals = intervals_of_slot("L40")
    l39_intervals = intervals_of_slot("L39")

    print(f"Parsed TCC2 (Theory) Intervals: {tcc2_intervals}")
    print(f"Parsed L40 (Lab) Intervals:    {l40_intervals}")
    print(f"Parsed L39 (Lab) Intervals:    {l39_intervals}")
    print("-" * 50)

    # 2. Check overlap logic directly
    clash_detected = any_overlap(tcc2_intervals, l40_intervals)
    no_clash_detected = any_overlap(tcc2_intervals, l39_intervals)

    # 3. Simulate Course Offerings to pass into the combo generator validator
    mock_mat1003 = {
        "course_code": "MAT1003",
        "name": "Applied Linear Algebra",
        "theory_slot": "TCC2",
    }
    mock_cse2001 = {
        "course_code": "CSE2001",
        "name": "Computer Organization and Architecture",
        "lab_slot": "L40",
    }
    
    combo_has_clash = combo_clash([mock_mat1003, mock_cse2001])

    # Assert and verify outputs
    success = True
    if not clash_detected:
        print("❌ FAILED: The system did not flag a clash between TCC2 and L40.")
        success = False
    else:
        print("✅ SUCCESS: The system successfully flags a conflict between TCC2 and L40.")

    if no_clash_detected:
        print("❌ FAILED: False positive! System falsely flags a clash between TCC2 and L39.")
        success = False
    else:
        print("✅ SUCCESS: TCC2 and L39 safely process without conflicts.")

    if not combo_has_clash:
        print("❌ FAILED: The course combo structure generator missed the time block error.")
        success = False
    else:
        print("✅ SUCCESS: Combo validator successfully blocks this conflicting timetable combination.")

    print("-" * 50)
    if success:
        print("🎉 ALL TESTS PASSED! Your slot layout mapping fix is completely solid.")
    else:
        print("⚠️ SOME TESTS FAILED. Double-check your utils/slots.py modifications.")


if __name__ == "__main__":
    test_wednesday_afternoon_clash()
